backend:
  name: github
  branch: main # change this to your branch
  repo: maliyao2023/my_fuwari # 1、change this to your repo
  site_domain: www.maliyao.com # 2、change this to your domain
  base_url: https://www.maliyao.com # 3、change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration

collections:
  - name: "post"
    label: "博文"
    folder: "src/content/post"
    create: true
    slug: "{{year}}.{{month}}.{{day}}_{{slug}}"
    
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "published", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "描述", name: "description", widget: "text" }
      - { label: "封面图", name: "image", widget: "image", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "分类", name: "category", widget: "string", required: false }
      - { label: "草稿", name: "draft", widget: "boolean", default: true }
      - { label: "语言", name: "lang", widget: "string", required: false, default: "zh-CN" }
      - { label: "正文", name: "body", widget: "markdown" }

media_folder: "src/assets/images" # 文件将被存储在仓库中的位置
public_folder: "src/assets/images" # 上传媒体文件的 src 属性
